export const EGYPT_GOVERNORATES = [
  'Alexandria',
  'Aswan',
  'Assiut',
  'Beheira',
  'Beni Suef',
  'Cairo',
  'Dakahlia',
  'Damietta',
  'Fayoum',
  'Gharbia',
  'Giza',
  'Ismailia',
  'Kafr El Sheikh',
  'Luxor',
  'Matrouh',
  'Menofia',
  'Minya',
  'New Valley',
  'North Sinai',
  'Port Said',
  'Qaliubiya',
  'Qena',
  'Red Sea',
  'Sharqia',
  'Sohag',
  'South Sinai',
  'Suez',
] as const;

export type EgyptGovernorate = (typeof EGYPT_GOVERNORATES)[number];
